name: Build and Publish Docker Image
on:
  push:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hiddenswitch/comfyui
jobs:
  build:
    runs-on: "ubuntu-latest"
    environment: Testing
    permissions:
      contents: read
      packages: write
    steps:
      - uses: insightsengineering/disk-space-reclaimer@v1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: "$oauthtoken"
          password: ${{ secrets.NVCR_NGC_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=latest-cuda,enable={{is_default_branch}}
            type=sha,prefix=
            type=sha,prefix=,suffix=-cuda
            type=semver,pattern={{version}}
            type=semver,pattern={{version}},suffix=-cuda
      - name: Build and push CUDA (NVIDIA) image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}